version:  "3.8"

services:
  jupyterlab:
    # command: sh -c "/bin/bash"
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8888:8888" # For jupyter notebook
    volumes:
      - .:/app:delegated
    command: sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/app --allow-root"