
visualization:
  realtime: True
  output_filepath: ./outputs/experiments/KITTI/visualization
  save_frames: False # Save frames for later video generation
  save_trajectory: True
  show_vo_trajectory: True
  show_angle_estimation: False
  show_end_result: True
  show_vio_frame: True
  show_innovation_history: True 
  set_lim_in_plot: False
  limits:
  fields:
    accelerometer: True
    gyroscope: True
    estimation: True
    image: True
    gps: True
    vo: True
    velocity: True
    angle: True
    state: False
    ground_truth: True
    ensemble: True