mode:
  log_level: debug
  log_sensor_data: True
  save_estimation: True
  save_output_debug_frames: True
  sensor_data_output_filepath: ../_debugging/sensor_out_uav.txt

visualization:
  realtime: True
  output_filepath: ../outputs
  save_frames: True
  save_trajectory: False
  show_vo_trajectory: True
  show_angle_estimation: False
  show_end_result: True
  show_vio_frame: True
  show_particles: False
  set_lim_in_plot: True
  show_innovation_history: False 
  limits:
    

dataset:
  type: uav
  mode: stream # NOTE: choose from (stream, live), and live is not implemented yet.
  root_path: ../../data/UAV
  variant: log0001
  sensors:
    # uav
    voxl_imu0: # 1000Hz
      selected: False
      dropout_ratio: 0.
      window_size: 100
    voxl_imu1: # 1000Hz
      selected: False
      dropout_ratio: 0.
      window_size: 1
    voxl_qvio_overlay: # NOTE: set show_vio_frame true to enable this field.
      selected: False
      dropout_ratio: 0.
      window_size: 1
    voxl_stereo:
      selected: True
      dropout_ratio: 0.
      window_size: 1
    px4_imu0: # 100Hz
      selected: True
      dropout_ratio: 0.
      window_size: 100
    px4_imu1: # 100Hz
      selected: False
      dropout_ratio: 0.
      window_size: 1
    px4_gps: 
      selected: False
      dropout_ratio: 0.
      window_size: 1
    px4_mag: 
      selected: True
      dropout_ratio: 0
      window_size: 1
    px4_vo: 
      selected: False
      dropout_ratio: 0.
      window_size: 1
    uav_custom_vo:
      selected: True
      dropout_ratio: 0.
      window_size: 1

    # kitti
    oxts_imu:
      selected: False
      dropout_ratio: 0
      window_size: 1
    oxts_ins: 
      selected: False
      dropout_ratio: 0
      window_size: 1
    oxts_gps: 
      selected: False
      dropout_ratio: 0
      window_size: 1
    kitti_color_image: # this is nothing to do with filter, but for visualization
      selected: False
      dropout_ratio: 0
      window_size: 1
      
    kitti_upward_leftward_velocity: # this is used only in experiment
      selected: False
      dropout_ratio: 0
      window_size: 1

report:
  export_error: False
  error_output_root_path: ../outputs/UAV
  kitti_pose_result_folder: ""
  location_only: False 

filter:
  type: ckf
  dimension: 2
  motion_model: kinematics # kinematics or velocity
  noise_type: default # default, dynamic, optimal 
  innovation_masking: False
  vo_velocity_only_update_when_failure: False
  params:
    #ukf
    alpha: 1.0
    beta: 2.0
    kappa: 0.0
    #pf
    particle_size: 1024
    resampling_algorithm: stratified # Select from: multinomial, redidual, systematic, stratified
    scale_for_ess_threshold: 0.5 # from 0. to 1.
    #enkf
    ensemble_size: 256

visual_odometry:
  mode:
    type: stereo # monocular
    save_traj: True
    save_poses_kitti_format: True
    save_output_debug_frames: True
    output_directory: results/seq_09_with_car_median
    log_level: debug
  
  stereo:
    algorithm: SGBM # BM
    speckle_window_size: 100
    median_filter: 3
    wsl_filter: False
    dynamic_depth: True

  detector:
    algorithm: sift # orb, superpoint, AKAZE, SURF
    no_of_keypoints: max
    homography: True 
    error_threshold: 30
    circular_matching: False

  matcher:
    algorithm: bf # FLANN
    ratio_test: 0.45 # set to 0 to disable
    dynamic_ratio: True

  motion_estimation:
    algorithm: iterative # Only 3D-2D correspondance currently available
    depth_limit: 200 #  depth_threshold < depth_limit
    depth_threshold: 125 # in meters
    x_correspondence_threshold: 200 # in pixels, set to zero to disable
    invalidate_cars: False