general:
  log_level: debug
  log_sensor_data: True
  save_estimation: True
  save_output_debug_frames: True
  sensor_data_output_filepath: ./_debugging/sensor_out.txt

visualization:
  realtime: False
  output_filepath: outputs/KITTI
  save_frames: False
  save_trajectory: False
  show_vo_trajectory: True
  show_angle_estimation: False
  show_end_result: True
  show_vio_frame: True
  show_particles: True
  set_lim_in_plot: False
  show_innovation_history: True 
  limits:
  fields:
    accelerometer: True
    gyroscope: True
    estimation: True
    image: True
    gps: True
    vo: True
    velocity: True
    angle: True
    beacon: False
    state: True
    leica: False
    ground_truth: False

dataset:
  type: kitti
  mode: stream # NOTE: choose from (stream, live), and live is not implemented yet.
  root_path: ./data/KITTI
  variant: "09" #NOTE: variant for kitti: 0016, 0020, 0027, 0033, 0067
  sensors:
    oxts_imu:
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10
    oxts_imu_unsynced:
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 100
    oxts_ins: 
      selected: False # select when motion_model is velocity
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10 # Hz
    oxts_gps: 
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10
    oxts_gps_unsynced: 
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 100
    kitti_stereo:
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
    kitti_custom_vo: # static vo data. Not working in realtime
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        simulate_delay: False
        min_confidence: 0.5
        max_confidence: 1.0
        avg_delay: 0.3 # seconds
    kitti_color_image: # this is nothing to do with filter, but for visualization
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
      
    kitti_upward_leftward_velocity: # this is used only in experiment
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:

report:
  export_error: False
  error_output_root_path: ../outputs/KITTI
  kitti_pose_result_folder: ""
  location_only: False 
  
filter:
  type: ekf # Select from: ekf, ukf, pf, enkf, ckf, srckf
  dimension: 2
  motion_model: velocity # kinematics or velocity
  noise_type: default # default, dynamic 
  innovation_masking: False
  vo_velocity_only_update_when_failure: False
  estimation_publishing_interval: 1.0 # In seconds
  is_imu_preintegrated: False
  compensate_gravity: True
  use_imu_preprocessing: False
  use_vo_relative_pose: False
  params:
    #ukf
    alpha: 1.
    beta: 2.0
    kappa: 0.0
    #pf
    particle_size: 2048
    resampling_algorithm: stratified # Select from: multinomial, redidual, systematic, stratified
    scale_for_ess_threshold: .5 # from 0. to 1.
    #enkf
    ensemble_size: 64


visual_odometry:
  type: monocular # Select from: monocular
  estimator: 2d2d # Select from: 2d2d, 3d3d, 2d3d
  camera_id: left
  depth_estimator: zoe_depth # Select from: zoe_depth
  feature_detector: sift # Select from: sift, orb, akaze, kaze, superpoint
  feature_matcher: brute_force # Select from: bf, flann
  use_advanced_detector: True
  solve_pose_max_itterations: 5
  params:
    # 2d2d
    max_features: 1000
    quality_level: 0.01
    min_distance: 7
    block_size: 21
    # 3d3d
    min_depth_threshold: 1
    max_depth_threshold: 40