general:
  log_level: debug
  log_sensor_data: True
  save_sensor_data: True
  save_estimation: True
  save_output_debug_frames: True
  sensor_data_output_filepath: ./.debugging/sensor_out.txt
  sensor_data_save_path: ./outputs/sensor_data

visualization:
  realtime: True
  output_filepath: ./outputs/experiments/KITTI/visualization
  save_frames: False # Save frames for later video generation
  save_trajectory: True
  show_vo_trajectory: True
  show_angle_estimation: False
  show_end_result: True
  show_vio_frame: True
  show_particles: False
  show_innovation_history: True 
  set_lim_in_plot: False
  limits:
  fields:
    accelerometer: True
    gyroscope: True
    estimation: True
    image: True
    gps: True
    vo: True
    velocity: True
    angle: True
    state: False
    ground_truth: True

dataset:
  type: kitti
  mode: stream # NOTE: choose from (stream, live), and live is not implemented yet.
  root_path: ./data/KITTI
  variant: "07" #NOTE: variant for kitti
  sensors:
    oxts_imu:
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10
        gyroscope_noise_density: 5.817764173314432e-05
        accelerometer_noise_density: 8.333333333333333e-05
        gyroscope_random_walk: 0.0005817764173314433
        accelerometer_random_walk: 0.0008333333333333333
    oxts_imu_unsynced:
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 100
    oxts_ins: 
      selected: False # select when motion_model is velocity
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10 # Hz
    oxts_gps: 
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10
    oxts_gps_unsynced: 
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 100
    kitti_stereo:
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        frequency: 10
    kitti_vo:
      selected: True
      dropout_ratio: 0
      window_size: 1
      args:
        
    kitti_color_image: # this is for visualization
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
      
    kitti_upward_leftward_velocity: # this is used only in experiment
      selected: False
      dropout_ratio: 0
      window_size: 1
      args:
      
report:
  export_error: False
  error_output_root_path: ../outputs/KITTI
  pose_result_dir: ""
  location_only: False 

filter:
  type: ekf # Select from: ekf, ukf, pf, enkf, ckf
  dimension: 2
  motion_model: velocity # kinematics or velocity
  innovation_masking: False
  is_imu_preintegrated: False
  compensate_gravity: True
  use_imu_preprocessing: False
  params:
    # ukf
    alpha: 1.0
    beta: 2.0
    kappa: 0.
    # pf
    particle_size: 2048
    resampling_algorithm: stratified # Select from: multinomial, redidual, systematic, stratified
    scale_for_ess_threshold: .8 # from 0. to 1.
    distribution: multivariate_student_t # Select from multivariate_normal, multivariate_student_t
    # enkf
    ensemble_size: 128
  sensors: # Sensor fields to be fused
    oxts_imu:
      fields: 
        - linear_acceleration
        - angular_velocity
    oxts_imu_unsynced:
      fields: 
        - linear_acceleration
        - angular_velocity
    oxts_gps: 
      fields: 
        - position
        # - heading_angle
    oxts_gps_unsynced: 
      fields: 
        - position
        # - heading_angle
    kitti_vo:
      fields: 
        - position
        # - linear_velocity
        # - orientation
    kitti_upward_leftward_velocity:
      fields: 
        - upward_velocity
        - leftward_velocity
  noise:
    type: default # default, adaptive
    params:
      alpha: 0.3 # 0 < alpha <= 1

visual_odometry:
  type: static # Select from: monocular, static (saved vo data)
  estimator: 2d3d # Select from: 2d2d, 2d3d, hybrid
  camera_id: left
  depth_estimator: dino_v2 # Select from: zoe_depth
  object_detector: segformer # Select from: yolo11 or segformer
  feature_detector: SIFT # Select from: sift, orb, akaze, kaze, superpoint
  feature_matcher: BF # Select from: bf, flann
  use_advanced_detector: True
  export_vo_data: False
  export_vo_data_path: ./data/KITTI/
  params: 
    # 2d2d
    confidence: 0.90
    ransac_reproj_threshold: 0.999
    matching_threshold: 0.45
    max_features: 1000
    # {'detector_matcher': ('SIFT', 'BF'), 'confidence': 0.9400000000000001, 'ransac_reproj_threshold': 1.0, 'matching_threshold': 0.5}
    object_detection_confidence: 0.7
    # Keypoints filtering
    border_threshold: 10
    response_threshold: 0.01
    size_min: 2.0
    size_max: 10.0
    depth_min: 1.0
    depth_max: 35.0
    min_number_of_keypoints: 300
  dynamic_objects:
    - truck
    - bus
    - sky

drone_config: