filter:
  type: pf # Select from: ekf, ukf, pf, enkf, ckf
  dimension: 2
  motion_model: kinematics # kinematics or velocity
  innovation_masking: False
  is_imu_preintegrated: False
  compensate_gravity: True
  use_imu_preprocessing: False
  params:
    # ukf
    alpha: 0.5
    beta: 2.0
    kappa: 0.
    # pf
    particle_size: 2048
    resampling_algorithm: stratified # Select from: multinomial, residual, systematic, stratified
    scale_for_ess_threshold: 0.5 # from 0. to 1.
    distribution: multivariate_normal # Select from multivariate_normal, multivariate_student_t
    # enkf
    ensemble_size: 128
  sensors: # Sensor fields to be fused
    oxts_imu:
      fields: 
        - linear_acceleration
        - angular_velocity
      noise:
        type: process # Select from: process, measurement
        scale: 1.0
        transformation: imu_noise_to_process_noise # This function should be defined in the same file and will be called in the code to convert the noise values into process noise
        params:
          gyroscope_noise_density: 5.817764173314432e-05
          accelerometer_noise_density: 8.333333333333333e-05
          gyroscope_random_walk: 0.0005817764173314433
          accelerometer_random_walk: 0.0008333333333333333
          dt: 0.1
    oxts_imu_unsynced:
      fields: 
        - linear_acceleration
        - angular_velocity
      noise:
        type: process # Select from: process, measurement
        scale: 1.0
        transformation: imu_noise_to_process_noise # This function should be defined in the same file and will be called in the code to convert the noise values into process noise
        params:
          gyroscope_noise_density: 5.817764173314432e-05
          accelerometer_noise_density: 8.333333333333333e-05
          gyroscope_random_walk: 0.0005817764173314433
          accelerometer_random_walk: 0.0008333333333333333
          dt: 0.01
    oxts_gps: 
      fields: 
        - position
        # - heading_angle
      noise:
        type: measurement # Select from: process, measurement
        scale: 1.0
        transformation: position_noise_to_measurement_noise  # This function should be defined in the same file and will be called in the code to convert the noise values into measurement noise
        params:
          position_noise: 2.0 # meters
    oxts_gps_unsynced: 
      fields: 
        - position
        # - heading_angle
      noise:
        type: measurement # Select from: process, measurement
        scale: 1.0
        transformation: position_noise_to_measurement_noise # This function should be defined in the same file and will be called in the code to convert the noise values into process noise
        params:
          position_noise: 2.0 # meters
    kitti_vo:
      fields: 
        - position
        - linear_velocity
        # - orientation
      noise:
        type: measurement # Select from: process, measurement
        scale: 1.0
        transformation: vo_noise_to_measurement_noise # This function should be defined in the same file and will be called in the code to convert the noise values into measurement noise
        params:
          vo_position_noise: 5.0 # meters
          vo_velocity_noise: 2.0 # m/s
          vo_orientation_noise: 3.0 # degrees
    kitti_upward_leftward_velocity:
      fields: 
        - upward_velocity
        - leftward_velocity
      noise:
        type: measurement # Select from: process, measurement
        scale: 1.0
        transformation: lateral_velocity_noise_to_measurement_noise # This function should be defined in the same file and will be called in the code to convert the noise values into measurement noise
        params:
          upward_velocity_noise: 0.01
          leftward_velocity_noise: 0.01
  noise_management:
    type: default # default, adaptive
    params:
      alpha: 0.3 # 0 < alpha <= 1
