/**
 * voxl-mavlink-server Configuration File
 *
 * primary_static_gcs_ip & secondary_static_gcs_ip
 *    These configure voxl-mavlink-server to automatically try to connect to
 *    up to two known static GCS units. Set to empty or NULL if you don't want
 *    to use this and you want the GCS to initialize the connection instead.
 *    Note the default IP for the primary link is 192.168.8.10 which is the
 *    first IP that VOXL DHCP serves when connecting in wifi softap mode.
 *
 *    DON'T set either of these ip addresses to localhost, these are meant
 *    for external ground control stations. For mavsdk and mavros communication
 *    locally, set the 'en_localhost_mavlink_udp' flag in voxl-vision-hub's
 *    /etc/modalai/voxl-vision-hub.conf file instead.
 *
 *
 * autopilot_uart_bus        - primary uart bus, default 5 for voxl flight 
 * autopilot_uart_baudrate   - default 921600
 * autopilot_uart_backup_bus - backup port auto-selected if primary is not connected
 *                             set to 12 for VOXL J11
 * en_external_fc_timesync   - enable responding to timesync messages
 *                                   (enabled by default)
 * udp_mtu - maximum transfer unit for UDP packets back to GCS. voxl-mavlink-server
 *           will bundle up backets for the GCS into a single UDP packet with 
 *           a maxium size of this. This might help with some radios.
 *           This feature is off by default to let the network stack handle aggregation.
 *           Set to 0 to disable this feature and send one UDP packet per msg.
 *           Set to something like 500 to bundle a handful of packets together.
 *
 */
{
	"primary_static_gcs_ip":	"192.168.8.84",
	"secondary_static_gcs_ip":	"192.168.8.57",
	"autopilot_uart_backup_bus":	12,
	"autopilot_uart_bus":	5,
	"autopilot_uart_baudrate":	921600,
	"en_external_ap_timesync":	1,
	"en_external_ap_heartbeat":	1,
	"udp_mtu":	0,
	"gcs_timeout_s":	4.5
}
